# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m

# Android build settings
android.useAndroidX=true
android.enableJetifier=true
android.targetSdkVersion=34
android.compileSdkVersion=34
android.minSdkVersion=26

# Kotlin settings
kotlin.code.style=official

# Enable Build Caching
org.gradle.caching=true

# Enable Parallel Build
org.gradle.parallel=true

# Enable Configuration Caching
org.gradle.configuration-cache=false

# Version catalog
version.code=1
version.name=1.0.0